module.exports = {
  docs: [
    {
      type: 'category',
      label: '📚 Textbook',
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    },
  ],
};
